### ISSUE TITLE
Default password to login

### ISSUE THREAD

**Issue by kpdillon** [martingjohn/guacamole#9]
Hi - what is the default password to login?  I tried guacadmin/guacadmin and it does not work.

**Comment by martingjohn** [comment]
It's whatever you put in the config xml - see http://guacamole.apache.org/doc/gug/configuring-guacamole.html#user-mapping for more details. You'll obviously also need to set your rdp/vnc/ssh targets in there too

**Comment by kpdillon** [comment]
Got it now.  Thank you!  Your package is the first to work on my Synology!

**Comment by martingjohn** [comment]
Glad it works, your NAS is probably a non-AMD64 architecture which mean that a lot won't support it, I had similar issues with my raspberry pi and had to do a number of builds from scratch. https://www.mjpitz.com/blog/2019/05/07/docker-buildx/ is quite helpful if you want to make a multi-arch build - this also lets you build it on your desktop which might be a lot faster than building on the NAS.
